_BASE_: "../Base-RCNN-FPN.yaml"
MODEL:
  WEIGHTS: "checkpoints/voc/faster_rcnn/faster_rcnn_R_101_FPN_base3/model_reset_surgery.pth"
  MASK_ON: False
  RESNETS:
    DEPTH: 101
  ROI_HEADS:
    NUM_CLASSES: 11
    # NUM_CLASSES: 20
    OUTPUT_LAYER: "CosineSimOutputLayers"
    FREEZE_FEAT: True
  BACKBONE:
    FREEZE: True
  PROPOSAL_GENERATOR:
    FREEZE: True
INPUT:
  MIN_SIZE_TRAIN: (80, 160, 240, 320, 480)
  MIN_SIZE_TEST: 160
  # MIN_SIZE_TRAIN: (480, 512, 544, 576, 608, 640, 672, 704, 736, 768, 800)
  # MIN_SIZE_TEST: 800
DATASETS:
  # TRAIN: ('digits_train',)
  TRAIN: ('digits_train_1shot_seed1', )
  TEST: ('digits_val',)
SOLVER:
  IMS_PER_BATCH: 16
  BASE_LR: 0.0001
  STEPS: (3000,)
  # STEPS: (3000,)
  MAX_ITER: 4000
  # MAX_ITER: 4000
  CHECKPOINT_PERIOD: 200
  # CHECKPOINT_PERIOD: 500
  WARMUP_ITERS: 0
OUTPUT_DIR: "checkpoints/voc/faster_rcnn/train_1shot"